
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/my_job
    volumes:
      - ./frontend/my_job:/app
      - /app/node_modules
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80" # Expose port 80 for HTTP traffic
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
