version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      # This is the corrected healthcheck. It's more reliable than the previous one.
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "fullstack_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/my_job
    volumes:
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:

