version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fullstack_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    # Ports are no longer exposed directly to the host
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=fullstack_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend/my_job
    # Ports are no longer exposed directly to the host
    volumes:
      - ./frontend/my_job:/app
      - /app/node_modules
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80" # Expose port 80 to the outside world
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
