"""Add before/after images and PDF support to WorkOrder

Revision ID: 178469b9b9df
Revises: 
Create Date: 2025-07-07 14:43:23.955428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178469b9b9df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workorderfiles', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('workorderfiles', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('workorderfiles', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('workorderfiles', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('workorders', sa.Column('before_image_path', sa.String(length=500), nullable=True))
    op.add_column('workorders', sa.Column('after_image_path', sa.String(length=500), nullable=True))
    op.add_column('workorders', sa.Column('pdf_file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workorders', 'pdf_file_path')
    op.drop_column('workorders', 'after_image_path')
    op.drop_column('workorders', 'before_image_path')
    op.drop_column('workorderfiles', 'uploaded_at')
    op.drop_column('workorderfiles', 'mime_type')
    op.drop_column('workorderfiles', 'file_size')
    op.drop_column('workorderfiles', 'file_name')
    # ### end Alembic commands ###
