"""Remove frequency from work_orders

Revision ID: 25bf55bda243
Revises: 40d140293bb5
Create Date: 2025-07-15 15:36:36.218408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bf55bda243'
down_revision: Union[str, Sequence[str], None] = '40d140293bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workorders_frequency', table_name='workorders')
    op.drop_column('workorders', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workorders', sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_workorders_frequency', 'workorders', ['frequency'], unique=False)
    # ### end Alembic commands ###
