"""Make machine_id nullable in procedures

Revision ID: 40d140293bb5
Revises: ebcce073f513
Create Date: 2025-07-15 13:47:08.391861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d140293bb5'
down_revision: Union[str, Sequence[str], None] = 'ebcce073f513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedures', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedures', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
