"""caleda

Revision ID: 52b24dca61fb
Revises: 25bf55bda243
Create Date: 2025-07-15 16:00:57.844977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52b24dca61fb'
down_revision: Union[str, Sequence[str], None] = '25bf55bda243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('before_images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('after_images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('execution_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['workorders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_executions_id'), 'procedure_executions', ['id'], unique=False)
    op.add_column('procedures', sa.Column('pm_image_path', sa.String(length=500), nullable=True))
    op.add_column('procedures', sa.Column('next_due_date', sa.Date(), nullable=True))
    op.add_column('procedures', sa.Column('last_completed_date', sa.Date(), nullable=True))
    op.add_column('procedures', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('procedures', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedures', 'estimated_duration_minutes')
    op.drop_column('procedures', 'is_active')
    op.drop_column('procedures', 'last_completed_date')
    op.drop_column('procedures', 'next_due_date')
    op.drop_column('procedures', 'pm_image_path')
    op.drop_index(op.f('ix_procedure_executions_id'), table_name='procedure_executions')
    op.drop_table('procedure_executions')
    # ### end Alembic commands ###
