"""Add frequency column to workorders

Revision ID: 6bd7ed523e73
Revises: d7449cda3b8f
Create Date: 2025-07-19 09:30:42.558273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd7ed523e73'
down_revision: Union[str, Sequence[str], None] = 'd7449cda3b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workorders', sa.Column('frequency', sa.String(length=50), nullable=True))
    op.drop_index('ix_workorders_task', table_name='workorders')
    op.create_index('idx_workorder_type', 'workorders', ['type'], unique=False)
    op.drop_column('workorders', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workorders', sa.Column('task', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_index('idx_workorder_type', table_name='workorders')
    op.create_index('ix_workorders_task', 'workorders', ['task'], unique=False)
    op.drop_column('workorders', 'frequency')
    # ### end Alembic commands ###
