"""Add frequency column to procedures

Revision ID: 7b69e4ff8be6
Revises: b80e9f2715da
Create Date: 2025-07-15 11:05:29.647397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b69e4ff8be6'
down_revision: Union[str, Sequence[str], None] = 'b80e9f2715da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
