"""Add frequency column to procedures

Revision ID: b80e9f2715da
Revises: 442d64d1c57c
Create Date: 2025-07-15 10:56:18.556369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80e9f2715da'
down_revision: Union[str, Sequence[str], None] = '442d64d1c57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('frequency', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_procedures_frequency'), 'procedures', ['frequency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procedures_frequency'), table_name='procedures')
    op.drop_column('procedures', 'frequency')
    # ### end Alembic commands ###
