"""Add user table

Revision ID: d7449cda3b8f
Revises: 52b24dca61fb
Create Date: 2025-07-18 13:37:34.699912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7449cda3b8f'
down_revision: Union[str, Sequence[str], None] = '52b24dca61fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_executions', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.create_index('idx_procedure_execution_date', 'procedure_executions', ['scheduled_date'], unique=False)
    op.create_index('idx_procedure_execution_machine', 'procedure_executions', ['machine_id'], unique=False)
    op.create_index('idx_procedure_execution_procedure', 'procedure_executions', ['procedure_id'], unique=False)
    op.create_index('idx_procedure_execution_status', 'procedure_executions', ['status'], unique=False)
    op.create_foreign_key(None, 'procedure_executions', 'machines', ['machine_id'], ['id'])
    op.create_index('idx_procedure_frequency', 'procedures', ['frequency'], unique=False)
    op.create_index('idx_procedure_title', 'procedures', ['title'], unique=False)
    op.drop_constraint('procedures_machine_id_fkey', 'procedures', type_='foreignkey')
    op.drop_column('procedures', 'machine_id')
    op.drop_column('procedures', 'last_completed_date')
    op.drop_column('procedures', 'next_due_date')
    op.drop_column('procedures', 'estimated_duration_minutes')
    op.drop_column('procedures', 'is_active')
    op.drop_column('procedures', 'pm_image_path')
    op.add_column('workorders', sa.Column('procedure_id', sa.Integer(), nullable=True))
    op.create_index('idx_workorder_due_date', 'workorders', ['due_date'], unique=False)
    op.create_index('idx_workorder_property', 'workorders', ['property_id'], unique=False)
    op.create_index('idx_workorder_status', 'workorders', ['status'], unique=False)
    op.create_foreign_key(None, 'workorders', 'procedures', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workorders', type_='foreignkey')
    op.drop_index('idx_workorder_status', table_name='workorders')
    op.drop_index('idx_workorder_property', table_name='workorders')
    op.drop_index('idx_workorder_due_date', table_name='workorders')
    op.drop_column('workorders', 'procedure_id')
    op.add_column('procedures', sa.Column('pm_image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('procedures', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('procedures', sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('procedures', sa.Column('next_due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('procedures', sa.Column('last_completed_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('procedures', sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('procedures_machine_id_fkey', 'procedures', 'machines', ['machine_id'], ['id'])
    op.drop_index('idx_procedure_title', table_name='procedures')
    op.drop_index('idx_procedure_frequency', table_name='procedures')
    op.drop_constraint(None, 'procedure_executions', type_='foreignkey')
    op.drop_index('idx_procedure_execution_status', table_name='procedure_executions')
    op.drop_index('idx_procedure_execution_procedure', table_name='procedure_executions')
    op.drop_index('idx_procedure_execution_machine', table_name='procedure_executions')
    op.drop_index('idx_procedure_execution_date', table_name='procedure_executions')
    op.drop_column('procedure_executions', 'machine_id')
    # ### end Alembic commands ###
