"""Add frequency column to workorders and procedures

Revision ID: ebcce073f513
Revises: 7b69e4ff8be6
Create Date: 2025-07-15 13:23:10.748930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcce073f513'
down_revision: Union[str, Sequence[str], None] = '7b69e4ff8be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workorders', sa.Column('frequency', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_workorders_frequency'), 'workorders', ['frequency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workorders_frequency'), table_name='workorders')
    op.drop_column('workorders', 'frequency')
    # ### end Alembic commands ###
