"""Add before_images and after_images to workorders

Revision ID: ec4a459dacbe
Revises: 46c5671ded58
Create Date: 2025-07-09 15:51:49.807630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec4a459dacbe'
down_revision: Union[str, Sequence[str], None] = '46c5671ded58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workorders', sa.Column('before_images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('workorders', sa.Column('after_images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workorders', 'after_images')
    op.drop_column('workorders', 'before_images')
    # ### end Alembic commands ###
